version: '2'
services:
  db:
    image: postgres
    environment:
      - POSTGRES_PASSWORD=${RAILS_POSTGRES_PASSWORD}
      - POSTGRES_USER=rails
      - POSTGRES_DB=rails
    volumes:
        - ./postgres-data:/var/lib/postgresql/data
    ports:
      - 5432:5432
  batukeira:
    build: .
    entrypoint: /Batukeira/entrypoint.sh
    environment:
      - RAILS_POSTGRES_PASSWORD=${RAILS_POSTGRES_PASSWORD}
    volumes:
      - .:/Batukeira
    ports:
      - 3000:3000
    depends_on:
      - db